const express = require("express");
const Router = express.Router();
const ProductsData = require("./Products.routes.js");
const Credit = require("./Credit.routes.js");
const Business = require("./Business.routes.js");
const admin = require("./Admin.routes.js");
const MaxMin = require("./MaxMin.Routes.js");
// Credit;
const Expences = require("./Expences.routes.js");
const Employee = require("./Employee.routes.js");
const updateRouters = require("./UpdateTables.routes.js");
const Transaction = require("./Transaction.routes.js");
const Login = require("./Login.routes.js");
const User = require("./Users.Routes.js");
Router.use(User);
Router.use(MaxMin);
Router.use(Login);
Router.use(Expences);
Router.use(updateRouters);
Router.use(ProductsData);
Router.use(Transaction);
Router.use(Credit);
Router.use(Business);
Router.use(admin);
Router.use(Employee);
module.exports = Router;
